import React, { useState, useRef, useCallback, useMemo, useEffect } from 'react';
import { 
  Upload, 
  Search, 
  Trash2, 
  Copy, 
  Check, 
  Info, 
  Sparkles, 
  Flame, 
  RefreshCw, 
  ArrowLeft, 
  Download, 
  CheckCircle2, 
  Terminal, 
  Grid, 
  FileCode,
  X,
  FileCheck2,
  Youtube,
  Lock,
  Unlock
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';

// Define SearchResult structure for display (strictly matching requirements)
interface FeatureResult {
  featureName: string;
  rva: string;
}

// Predefined Smart Feature Mapping database
const SMART_MAPPINGS = [
  { func: "IsHighFPS120Open", feature: "120 FPS Unlocker", type: "bool" },
  { func: "get_CanBeLockedByAimAssist", feature: "Aim Assist", type: "bool" },
  { func: "SetAimRotation", feature: "Aimbot Use", type: "void" },
  { func: "SyncWeaponAmmoInClip", feature: "Ammo In Clip", type: "void" },
  { func: "SetupModule", feature: "Black Body", type: "void" },
  { func: "get_IsSwimSurf", feature: "Camera Hack", type: "bool" },
  { func: "get_OffsetForNormal", feature: "Camera View (Zoom Out)", type: "float" },
  { func: "get_UserGems", feature: "Diamond Hack", type: "int" },
  { func: "GetDisableFriendSpectateSetting", feature: "Disable Spectate", type: "bool" },
  { func: "ADBBMDMEFNO", feature: "Double Gun", type: "bool" },
  { func: "get_FSModeUseMedikitFasterRate", feature: "Fast Blood Wrap", type: "float" },
  { func: "get_InSwapWeaponCD", feature: "Fast Gun", type: "float" },
  { func: "get_FSModeUseMedikitFasterRate", feature: "Fast Medkit (2.25s)", type: "float" },
  { func: "get_FastAutoReloadSpeed", feature: "Fast Reload", type: "float" },
  { func: "OnStartChangeWeapon", feature: "Fast Weapon Switch", type: "void" },
  { func: "IsFemale", feature: "Female Model Hack", type: "bool" },
  { func: "AOCFOHFIAAM", feature: "Fix Crash", type: "bool" },
  { func: "BNFAGNBHHIF", feature: "Ghost Hack", type: "bool" },
  { func: "EAGIPMCDBIF", feature: "Ghost Hack 2", type: "bool" },
  { func: "get_IsGod", feature: "Gold Body", type: "bool" },
  { func: "get_UserCoins", feature: "Gold Hack", type: "int" },
  { func: "get_fog", feature: "HD Map / No Fog", type: "float" },
  { func: "get_MaxJumpHeight", feature: "High Jump", type: "float" },
  { func: "IsOnlineGame", feature: "Lobby Kill", type: "bool" },
  { func: "OnPreparationCancel", feature: "Medkit Run", type: "void" },
  { func: "IsFreeMove", feature: "Movement Shoot", type: "bool" },
  { func: "IsPlayerReadyNeedDelay", feature: "No Delay", type: "bool" },
  { func: "GetScatterRate", feature: "No Recoil", type: "float" },
  { func: "IsSightingUIAvailable", feature: "No Scope", type: "bool" },
  { func: "get_IsSpecialName", feature: "NPC Name", type: "bool" },
  { func: "get_ResetGuest", feature: "Reset Guest", type: "bool" },
  { func: "IsFreeMove", feature: "Run & Shoot", type: "bool" },
  { func: "RequestStartSwimmingSurfing", feature: "Run Under Water", type: "bool" },
  { func: "GetWeaponRunSpeedScale", feature: "Speed Hack", type: "float" },
  { func: "LHGGPDLOPAH", feature: "Teleport Kill", type: "bool" },
  { func: "get_IsAmmoFree", feature: "Unlimited Ammo", type: "bool" },
  { func: "IsUnlimitedGloowall", feature: "Unlimited Gloo Wall", type: "bool" },
  { func: "IsUnlimitedThrowables", feature: "Unlimited Grenades", type: "bool" },
  { func: "IsCelebrity", feature: "V Badge", type: "bool" },
  { func: "UseHighQualityAvatar", feature: "White Body", type: "void" },
  { func: "MoveNext", feature: "White Body", type: "bool" }
];

// Extract unique features
const UNIQUE_FEATURES = Array.from(new Set(SMART_MAPPINGS.map(m => m.feature))).sort();

// Predefined mock dump.cs for local sandbox demonstration
const SAMPLE_DUMP_CS = `// Generated by Il2CppDumper v6.4.15
// Namespace: 
public class GameManager : MonoBehaviour
{
	// RVA: 0x7F17870 Offset: 0x7F17870 VA: 0xACF8D870
	public static bool IsHighFPS120Open() { }

	// RVA: 0x521B780 Offset: 0x521B780 VA: 0xBC1122
	private int get_UserCoins() { }

	// RVA: 0x1A2B3C4 Offset: 0x1A2B3C4 VA: 0xDEB001
	public bool get_CanBeLockedByAimAssist() { }
}

public class WeaponManager : MonoBehaviour
{
	// RVA: 0xFB1374 Offset: 0xFB1374 VA: 0x9F8E7D
	public float get_InSwapWeaponCD() { }

	// RVA: 0x334455 Offset: 0x334455 VA: 0x77334455
	private bool ADBBMDMEFNO() { }

	// RVA: 0xAB9988 Offset: 0xAB9988 VA: 0x88AB9988
	public float get_fog() { }
}
`;

// Extract a single function block completely, including preceding comments and multi-line body
const extractFullFunction = (content: string, funcName: string, targetRva?: string): string => {
  if (!content || !funcName) return '';
  const contentLower = content.toLowerCase();
  const funcLower = funcName.toLowerCase();
  const funcLen = funcName.length;
  
  let index = 0;
  let bestFallback = '';

  while (true) {
    index = contentLower.indexOf(funcLower, index);
    if (index === -1) break;
    
    // Check word boundaries
    const prevChar = index > 0 ? content[index - 1] : '';
    const nextChar = index + funcLen < content.length ? content[index + funcLen] : '';
    const isWordCharBefore = /[a-zA-Z0-9_]/.test(prevChar);
    const isWordCharAfter = /[a-zA-Z0-9_]/.test(nextChar);
    
    if (!isWordCharBefore && !isWordCharAfter) {
      // Find the start of the line where funcName is declared
      let lineStart = content.lastIndexOf('\n', index);
      lineStart = lineStart === -1 ? 0 : lineStart + 1;
      
      // Find preceding comments (RVA lines)
      let firstCommentLineStart = lineStart;
      let scanIndex = lineStart;
      let linesChecked = 0;
      const maxBackwardLines = 15;
      
      while (scanIndex > 0 && linesChecked < maxBackwardLines) {
        const prevNewline = content.lastIndexOf('\n', scanIndex - 2);
        const prevLineStart = prevNewline === -1 ? 0 : prevNewline + 1;
        const prevLine = content.substring(prevLineStart, scanIndex).trim();
        linesChecked++;
        
        if (prevLine.startsWith('//')) {
          firstCommentLineStart = prevLineStart;
        } else if (prevLine === '' || prevLine.includes('class ') || prevLine.includes('struct ') || prevLine.includes('{') || prevLine.includes('}')) {
          break;
        } else {
          break;
        }
        scanIndex = prevLineStart;
      }
      
      // Now find the end of the function
      let lineEnd = content.indexOf('\n', index);
      if (lineEnd === -1) lineEnd = content.length;
      
      const signatureLine = content.substring(lineStart, lineEnd);
      let extractedBlock = '';
      
      // If it's inline `{ }`
      if (signatureLine.includes('{') && signatureLine.includes('}')) {
        extractedBlock = content.substring(firstCommentLineStart, lineEnd).trim();
      } else {
        // Multi-line scan
        let braceCount = 0;
        let foundBrace = false;
        let scanForwardIndex = lineStart;
        let forwardLinesCount = 0;
        let finalEndIndex = lineEnd;
        
        while (scanForwardIndex < content.length && forwardLinesCount < 30) {
          const nextNewline = content.indexOf('\n', scanForwardIndex);
          const currentLineEnd = nextNewline === -1 ? content.length : nextNewline;
          const currentLine = content.substring(scanForwardIndex, currentLineEnd);
          
          for (let i = 0; i < currentLine.length; i++) {
            const char = currentLine[i];
            if (char === '{') {
              braceCount++;
              foundBrace = true;
            } else if (char === '}') {
              braceCount--;
            }
          }
          
          finalEndIndex = currentLineEnd;
          if (foundBrace && braceCount === 0) {
            break;
          }
          
          if (nextNewline === -1) break;
          scanForwardIndex = nextNewline + 1;
          forwardLinesCount++;
        }
        extractedBlock = content.substring(firstCommentLineStart, finalEndIndex).trim();
      }

      if (extractedBlock) {
        // If targetRva is specified and this block matches it, return immediately
        if (targetRva && targetRva !== 'Not Found') {
          if (extractedBlock.includes(targetRva)) {
            return extractedBlock;
          }
        }
        
        if (!bestFallback) {
          bestFallback = extractedBlock;
        }
      }
    }
    
    index += funcLen;
  }
  
  return bestFallback;
};

// Find the correct function body even if a feature has multiple mapping functions
const getFunctionBodyForFeature = (feature: string, rva: string, fileContent: string): { body: string; funcName: string } => {
  const mappings = SMART_MAPPINGS.filter(m => m.feature === feature);
  
  // Try to match the function that contains the target RVA
  for (const mapping of mappings) {
    const body = extractFullFunction(fileContent, mapping.func, rva);
    if (body && rva && rva !== 'Not Found' && body.includes(rva)) {
      return { body, funcName: mapping.func };
    }
  }
  
  // Fallback to any matching function signature
  for (const mapping of mappings) {
    const body = extractFullFunction(fileContent, mapping.func);
    if (body) {
      return { body, funcName: mapping.func };
    }
  }
  
  return { body: '', funcName: '' };
};

// C# Token-based syntax highlighter for code display
const highlightCSharp = (code: string): React.ReactNode => {
  if (!code) return null;
  const lines = code.split('\n');
  
  return lines.map((line, lineIdx) => {
    const trimmed = line.trim();
    if (trimmed.startsWith('//')) {
      return (
        <div key={lineIdx} className="text-slate-500 italic">
          {line}
        </div>
      );
    }
    
    // Regex split to capture words, spaces, symbols
    const tokens = line.split(/(\s+|[{}();,])/);
    
    return (
      <div key={lineIdx} className="text-slate-300">
        {tokens.map((token, tokenIdx) => {
          const trimmedToken = token.trim();
          if (!trimmedToken) {
            return <span key={tokenIdx}>{token}</span>;
          }
          
          if (['public', 'private', 'protected', 'internal'].includes(trimmedToken)) {
            return <span key={tokenIdx} className="text-rose-400 font-semibold">{token}</span>;
          }
          if (['static', 'virtual', 'override', 'readonly', 'const'].includes(trimmedToken)) {
            return <span key={tokenIdx} className="text-amber-400">{token}</span>;
          }
          if (['bool', 'int', 'float', 'double', 'void', 'string', 'class', 'struct'].includes(trimmedToken)) {
            return <span key={tokenIdx} className="text-emerald-400 font-medium">{token}</span>;
          }
          if (trimmedToken.startsWith('0x') || /^\d+$/.test(trimmedToken)) {
            return <span key={tokenIdx} className="text-blue-400">{token}</span>;
          }
          if (trimmedToken.startsWith('//')) {
            return <span key={tokenIdx} className="text-slate-500 italic">{token}</span>;
          }
          
          return <span key={tokenIdx}>{token}</span>;
        })}
      </div>
    );
  });
};

export default function App() {
  // Navigation & File States
  const [view, setView] = useState<'upload' | 'scanning' | 'results'>('upload');
  const [fileContent, setFileContent] = useState<string>('');
  const [fileName, setFileName] = useState<string>('');
  const [fileSize, setFileSize] = useState<number>(0);
  const [lineCount, setLineCount] = useState<number>(0);
  const [isDemo, setIsDemo] = useState<boolean>(false);

  // Scanning states
  const [isBulkScanning, setIsBulkScanning] = useState<boolean>(false);
  const [bulkScanProgress, setBulkScanProgress] = useState<number>(0);
  const [bulkScanResults, setBulkScanResults] = useState<Record<string, string>>({});
  const [bulkScanTime, setBulkScanTime] = useState<number>(0);
  const [hasRunBulkScan, setHasRunBulkScan] = useState<boolean>(false);

  // UI display & filter states
  const [searchQuery, setSearchQuery] = useState<string>('');
  const [resultsLayout, setResultsLayout] = useState<'cards' | 'plain'>('cards');
  const [copiedId, setCopiedId] = useState<string | null>(null);
  const [isDragging, setIsDragging] = useState<boolean>(false);
  const [errorMessage, setErrorMessage] = useState<string>('');

  // Modal / Details Panel states
  const [selectedFeatureForModal, setSelectedFeatureForModal] = useState<string | null>(null);
  const [modalFunctionBody, setModalFunctionBody] = useState<string>('');
  const [modalRva, setModalRva] = useState<string>('');
  const [modalType, setModalType] = useState<string>('');
  const [modalFuncName, setModalFuncName] = useState<string>('');
  const [modalCopiedType, setModalCopiedType] = useState<'rva' | 'code' | null>(null);

  // YouTube Subscription Gate states
  const [isGateUnlocked, setIsGateUnlocked] = useState<boolean>(() => {
    try {
      return localStorage.getItem('internal_gate_unlocked') === 'true';
    } catch {
      return false;
    }
  });
  const [hasClickedSubscribe, setHasClickedSubscribe] = useState<boolean>(false);
  const [gateShowWarning, setGateShowWarning] = useState<boolean>(false);

  useEffect(() => {
    // 0. Centralized Ad Click Handler
    const handleAdClick = (e: MouseEvent) => {
      // Safely scan the global window object for any loaded CPM or popunder functions to invoke them
      try {
        for (const key in window) {
          if (
            key.startsWith('__') || 
            key.includes('pop') || 
            key.includes('ad') || 
            key.includes('cpm') || 
            key.includes('effective')
          ) {
            const val = (window as any)[key];
            if (typeof val === 'function') {
              try {
                val();
              } catch (err) {}
            }
          }
        }
      } catch (err) {}
    };
    document.addEventListener('click', handleAdClick, true);

    // 1. Disable right-click context menu
    const handleContextMenu = (e: MouseEvent) => {
      e.preventDefault();
    };
    document.addEventListener('contextmenu', handleContextMenu);

    // 2. Disable common shortcuts (Ctrl+U, Ctrl+S, Ctrl+Shift+I, Ctrl+Shift+J, Ctrl+Shift+C, F12)
    const handleKeyDown = (e: KeyboardEvent) => {
      const isCtrlOrMeta = e.ctrlKey || e.metaKey;
      
      // Ctrl+U
      if (isCtrlOrMeta && (e.key === 'u' || e.key === 'U' || e.keyCode === 85)) {
        e.preventDefault();
        return;
      }
      // Ctrl+S
      if (isCtrlOrMeta && (e.key === 's' || e.key === 'S' || e.keyCode === 83)) {
        e.preventDefault();
        return;
      }
      // Ctrl+Shift+I / J / C
      if (isCtrlOrMeta && e.shiftKey && (
        e.key === 'I' || e.key === 'i' || e.keyCode === 73 ||
        e.key === 'J' || e.key === 'j' || e.keyCode === 74 ||
        e.key === 'C' || e.key === 'c' || e.keyCode === 67
      )) {
        e.preventDefault();
        return;
      }
      // F12
      if (e.key === 'F12' || e.keyCode === 123) {
        e.preventDefault();
        return;
      }
    };
    document.addEventListener('keydown', handleKeyDown);

    return () => {
      document.removeEventListener('contextmenu', handleContextMenu);
      document.removeEventListener('keydown', handleKeyDown);
      document.removeEventListener('click', handleAdClick, true);
    };
  }, []);

  const fileInputRef = useRef<HTMLInputElement>(null);

  // Buffer lines count helper
  const countLines = (text: string): number => {
    let count = 1;
    let pos = 0;
    while ((pos = text.indexOf('\n', pos)) !== -1) {
      count++;
      pos++;
    }
    return count;
  };

  // Perform the physical, lightning-fast scan
  const executePhysicalScan = useCallback((content: string): { results: Record<string, string>; duration: number } => {
    const startTime = performance.now();
    const results: Record<string, string> = {};
    const contentLower = content.toLowerCase();
    const contentLen = content.length;

    UNIQUE_FEATURES.forEach((feature) => {
      // Find the corresponding mappings for this feature
      const mappings = SMART_MAPPINGS.filter(m => m.feature === feature);
      let foundRVA = 'Not Found';

      for (const mapping of mappings) {
        const funcName = mapping.func;
        const funcLower = funcName.toLowerCase();
        const funcLen = funcName.length;
        let index = 0;

        while (true) {
          index = contentLower.indexOf(funcLower, index);
          if (index === -1) break;

          // Verify whole word boundaries
          const prevChar = index > 0 ? content[index - 1] : '';
          const nextChar = index + funcLen < contentLen ? content[index + funcLen] : '';
          const isWordCharBefore = /[a-zA-Z0-9_]/.test(prevChar);
          const isWordCharAfter = /[a-zA-Z0-9_]/.test(nextChar);

          if (!isWordCharBefore && !isWordCharAfter) {
            // Found matching identifier, now find its preceding // RVA: line
            let lineStart = content.lastIndexOf('\n', index);
            lineStart = lineStart === -1 ? 0 : lineStart + 1;

            let scanIndex = lineStart;
            let rvaLine = '';
            let linesChecked = 0;
            const maxBackwardLines = 10;

            while (scanIndex > 0 && linesChecked < maxBackwardLines) {
              let prevNewline = content.lastIndexOf('\n', scanIndex - 2);
              let prevLineStart = prevNewline === -1 ? 0 : prevNewline + 1;
              let prevLine = content.substring(prevLineStart, scanIndex).trim();
              linesChecked++;

              if (prevLine.startsWith('// RVA:')) {
                rvaLine = prevLine;
                break;
              }
              if (prevLine.includes('class ') || prevLine.includes('struct ') || prevLine.includes('{') || prevLine.includes('}')) {
                break;
              }
              scanIndex = prevLineStart;
            }

            if (rvaLine) {
              const rvaMatch = rvaLine.match(/RVA:\s*(0x[0-9A-Fa-f]+)/i);
              if (rvaMatch) {
                foundRVA = rvaMatch[1];
                break; // Found matching RVA, skip further instances
              }
            }
          }
          index += funcLen;
        }

        if (foundRVA !== 'Not Found') {
          break; // Found the value, skip remaining alternate method signatures
        }
      }

      results[feature] = foundRVA;
    });

    const endTime = performance.now();
    return {
      results,
      duration: Math.round(endTime - startTime)
    };
  }, []);

  // Integrated, premium animated scanner controller
  const startScanningProcess = useCallback((content: string, name: string, size: number, isSample: boolean = false) => {
    setFileContent(content);
    setFileName(name);
    setFileSize(size);
    setLineCount(countLines(content));
    setIsDemo(isSample);
    setErrorMessage('');

    // Trigger visual loading screen
    setView('scanning');
    setBulkScanProgress(0);
    setIsBulkScanning(true);

    let progress = 0;
    const interval = setInterval(() => {
      progress += Math.floor(Math.random() * 8) + 4;
      if (progress >= 100) {
        progress = 100;
        clearInterval(interval);

        // Run actual heavy-duty parsing
        const scan = executePhysicalScan(content);

        setTimeout(() => {
          setBulkScanResults(scan.results);
          setBulkScanTime(scan.duration);
          setIsBulkScanning(false);
          setHasRunBulkScan(true);
          setView('results');
        }, 400); // Breathe at 100% for transition smoothness
      } else {
        setBulkScanProgress(progress);
      }
    }, 45); // Completes loading screen sequence in ~1 second
  }, [executePhysicalScan]);

  // Handle uploaded/dragged files
  const handleFile = (file: File) => {
    if (!file.name.endsWith('.cs') && !file.name.endsWith('.txt')) {
      setErrorMessage('Please upload a valid Unity dump.cs or text file.');
      return;
    }

    const reader = new FileReader();
    reader.onload = (e) => {
      const text = e.target?.result as string;
      startScanningProcess(text, file.name, file.size);
    };
    reader.onerror = () => {
      setErrorMessage('Failed to read file. Please try again.');
    };
    reader.readAsText(file);
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files.length > 0) {
      handleFile(e.target.files[0]);
    }
  };

  // Drag-and-drop mechanics
  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(true);
  };

  const handleDragLeave = () => {
    setIsDragging(false);
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);
    if (e.dataTransfer.files && e.dataTransfer.files.length > 0) {
      handleFile(e.dataTransfer.files[0]);
    }
  };

  const triggerFileBrowser = () => {
    fileInputRef.current?.click();
  };

  // Sandbox demonstration builder
  const loadSandboxTemplate = () => {
    startScanningProcess(SAMPLE_DUMP_CS, 'sandbox_dump.cs', SAMPLE_DUMP_CS.length, true);
  };

  // State Clear / Back reset
  const handleClear = () => {
    setFileContent('');
    setFileName('');
    setFileSize(0);
    setLineCount(0);
    setBulkScanResults({});
    setHasRunBulkScan(false);
    setSearchQuery('');
    setErrorMessage('');
    setIsDemo(false);
    setView('upload');
  };

  // Format File Size
  const formattedFileSize = useMemo(() => {
    if (fileSize === 0) return '0.0 KB';
    const k = 1024;
    const sizes = ['Bytes', 'KB', 'MB'];
    const i = Math.floor(Math.log(fileSize) / Math.log(k));
    return parseFloat((fileSize / Math.pow(k, i)).toFixed(1)) + ' ' + sizes[i];
  }, [fileSize]);

  // Output Plaintext builder (Exactly [FUNCTION NAME]                 [RVA])
  const getFormattedResultsText = useCallback((filterText: string = '') => {
    let output = `[FUNCTION NAME]`.padEnd(32, ' ') + `[RVA]\n`;
    output += `------------------------------------------------\n`;

    const filtered = UNIQUE_FEATURES.filter(f => {
      const rva = bulkScanResults[f] || 'Not Found';
      const isFound = rva !== 'Not Found';
      return isFound && f.toLowerCase().includes(filterText.toLowerCase());
    });

    filtered.forEach((feature) => {
      const rva = bulkScanResults[feature];
      const mapping = SMART_MAPPINGS.find(m => m.feature === feature);
      const typeStr = mapping ? ` (${mapping.type.toUpperCase()})` : '';
      output += `${feature.padEnd(32, ' ')}${rva}${typeStr}\n`;
    });

    return output;
  }, [bulkScanResults]);

  const copyToClipboard = (text: string, id: string) => {
    navigator.clipboard.writeText(text);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 1500);
  };

  // Filtered features for card grid listing (only show found features)
  const filteredFeatures = useMemo(() => {
    return UNIQUE_FEATURES.filter(f => {
      const rva = bulkScanResults[f] || 'Not Found';
      const isFound = rva !== 'Not Found';
      return isFound && f.toLowerCase().includes(searchQuery.toLowerCase());
    });
  }, [searchQuery, bulkScanResults]);

  if (!isGateUnlocked) {
    return (
      <div className="min-h-screen bg-[#06060a] text-slate-100 font-sans flex flex-col justify-center items-center p-4 relative overflow-hidden selection:bg-red-500/30 selection:text-red-200">
        {/* Animated Background Gradients */}
        <div className="absolute top-1/4 left-1/4 w-[300px] h-[300px] sm:w-[450px] sm:h-[450px] bg-red-600/10 blur-[120px] rounded-full pointer-events-none animate-pulse duration-[8000ms]" />
        <div className="absolute bottom-1/4 right-1/4 w-[250px] h-[250px] sm:w-[400px] sm:h-[400px] bg-red-800/10 blur-[100px] rounded-full pointer-events-none animate-pulse duration-[6000ms]" />
        
        {/* Animated matrix grid overlay for premium hacker look */}
        <div 
          className="absolute inset-0 opacity-[0.02] pointer-events-none"
          style={{
            backgroundImage: `radial-gradient(circle, rgba(239, 68, 68, 0.15) 1px, transparent 1px)`,
            backgroundSize: '24px 24px'
          }}
        />

        <AnimatePresence mode="wait">
          <motion.div
            initial={{ opacity: 0, scale: 0.95, y: 15 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: -15 }}
            transition={{ duration: 0.45, ease: 'easeOut' }}
            className="w-full max-w-md bg-[#0a0a0f]/80 border border-red-500/20 backdrop-blur-2xl rounded-3xl p-6 sm:p-10 text-center relative shadow-[0_0_80px_rgba(239,68,68,0.12)] flex flex-col items-center gap-6"
          >
            {/* Top Red Glow Accent */}
            <div className="absolute top-0 left-1/2 -translate-x-1/2 w-48 h-1 bg-gradient-to-r from-transparent via-red-500 to-transparent rounded-full" />

            {/* Shield / Flame / YouTube Icon container */}
            <motion.div 
              initial={{ rotate: -10, scale: 0.9 }}
              animate={{ rotate: 0, scale: 1 }}
              transition={{ type: 'spring', delay: 0.1 }}
              className="w-16 h-16 bg-red-500/10 border border-red-500/25 rounded-2xl flex items-center justify-center shadow-[0_0_25px_rgba(239,68,68,0.15)] relative group"
            >
              <Youtube className="w-8 h-8 text-red-500 group-hover:scale-110 transition-transform duration-300" />
              <div className="absolute -top-1 -right-1 bg-red-500 text-white rounded-full p-0.5 shadow-md">
                <Lock className="w-3 h-3" />
              </div>
            </motion.div>

            {/* Typography */}
            <div className="space-y-2">
              <span className="text-[10px] font-mono font-bold tracking-[0.25em] text-red-500 uppercase block">
                EXCLUSIVITY PORTAL
              </span>
              <h2 className="text-xl sm:text-2xl font-black text-white font-display tracking-wider uppercase leading-tight">
                WELCOME TO <br />
                <span className="text-transparent bg-clip-text bg-gradient-to-r from-red-500 to-rose-400 drop-shadow-[0_0_15px_rgba(239,68,68,0.2)]">INTERNAL X CHEATS</span>
              </h2>
              <p className="text-xs sm:text-sm text-slate-400 leading-relaxed font-sans max-w-xs mx-auto mt-1">
                Subscribe to our YouTube channel to continue.
              </p>
            </div>

            {/* Divider */}
            <div className="w-full h-[1px] bg-red-950/15" />

            {/* Buttons Group */}
            <div className="w-full flex flex-col gap-3">
              {/* Subscribe on YouTube Button */}
              <a
                href="https://www.youtube.com/@internalxcheat"
                target="_blank"
                rel="noopener noreferrer"
                onClick={() => {
                  setHasClickedSubscribe(true);
                  setGateShowWarning(false);
                }}
                className="w-full text-xs font-bold uppercase tracking-wider font-display bg-red-600 hover:bg-red-500 text-white py-3.5 px-5 rounded-xl transition-all duration-300 shadow-[0_0_25px_rgba(220,38,38,0.4)] flex items-center justify-center gap-2.5 hover:scale-[1.02] active:scale-95 cursor-pointer relative overflow-hidden group"
              >
                <Youtube className="w-4.5 h-4.5 text-white animate-pulse" />
                <span>Subscribe on YouTube</span>
              </a>

              {/* Continue to Website Button */}
              <button
                onClick={() => {
                  if (hasClickedSubscribe) {
                    try {
                      localStorage.setItem('internal_gate_unlocked', 'true');
                    } catch (e) {
                      console.error(e);
                    }
                    setIsGateUnlocked(true);
                  } else {
                    setGateShowWarning(true);
                  }
                }}
                className={`w-full text-xs font-bold uppercase tracking-wider font-display py-3.5 px-5 rounded-xl transition-all duration-300 flex items-center justify-center gap-2.5 cursor-pointer border ${
                  hasClickedSubscribe 
                    ? 'bg-slate-900 hover:bg-slate-800 text-white border-red-500/30 hover:border-red-500/60 shadow-[0_0_20px_rgba(239,68,68,0.1)] hover:scale-[1.02] active:scale-95' 
                    : 'bg-slate-950/40 text-slate-500 border-slate-900/60 cursor-not-allowed opacity-75'
                }`}
              >
                {hasClickedSubscribe ? (
                  <>
                    <Unlock className="w-4 h-4 text-red-400 animate-pulse" />
                    <span>Continue to Website</span>
                  </>
                ) : (
                  <>
                    <Lock className="w-4 h-4 text-slate-600" />
                    <span>Continue to Website</span>
                  </>
                )}
              </button>
            </div>

            {/* Error/Warning Msg if clicked continue too early */}
            <AnimatePresence>
              {gateShowWarning && (
                <motion.div
                  initial={{ opacity: 0, y: -10 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -10 }}
                  className="bg-red-500/10 border border-red-500/20 rounded-xl p-3 text-[11px] font-medium text-red-400 flex items-center justify-center gap-2 w-full"
                >
                  <span>⚠️ Please click "Subscribe on YouTube" first to unlock.</span>
                </motion.div>
              )}
            </AnimatePresence>

            {/* Informational Subtext */}
            <div className="text-[10px] text-slate-500 leading-relaxed max-w-[280px] mx-auto mt-2 select-none">
              Clicking <span className="text-slate-400 font-semibold">Subscribe</span> opens our official channel in a new tab. After opening, you can immediately continue.
            </div>
          </motion.div>
        </AnimatePresence>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[#08080c] text-slate-100 font-sans flex flex-col selection:bg-red-500/30 selection:text-red-200 select-none">
      
      {/* Decorative Top Glow */}
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full max-w-7xl h-[120px] bg-red-600/10 blur-[100px] pointer-events-none rounded-full" />

      {/* Header bar */}
      <header className="border-b border-red-950/40 bg-[#0d0d12]/80 backdrop-blur-md sticky top-0 z-40 py-4.5 px-6 shadow-[0_1px_15px_rgba(0,0,0,0.4)]">
        <div className="max-w-7xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-gradient-to-tr from-red-600 to-red-500 rounded-xl flex items-center justify-center shadow-[0_0_20px_rgba(239,68,68,0.35)] transition-transform duration-300 hover:scale-105">
              <Flame className="w-5.5 h-5.5 text-white" />
            </div>
            <div>
              <h1 className="text-xl font-bold tracking-widest text-white font-display uppercase">
                INTERNAL X CHEATS
              </h1>
              <p className="text-[10px] text-red-500 uppercase tracking-widest font-bold">DUMP.CS RVA MAPPER</p>
            </div>
          </div>

          <div className="flex items-center gap-4">
            {view === 'results' && (
              <button
                onClick={handleClear}
                className="px-3.5 py-1.5 border border-red-500/20 hover:border-red-500/40 bg-red-950/10 hover:bg-red-950/30 text-red-400 hover:text-red-300 rounded-xl text-xs font-semibold tracking-wider font-display transition-all cursor-pointer flex items-center gap-1.5"
              >
                <ArrowLeft className="w-3.5 h-3.5" /> BACK TO UPLOAD
              </button>
            )}
            <div className="flex flex-col items-end border-l border-slate-800 pl-4">
              <span className="text-[9px] text-slate-500 uppercase tracking-wider">Engine status</span>
              {fileContent ? (
                <span className="text-[11px] font-mono text-red-500 flex items-center gap-1.5 font-bold">
                  <span className="w-2 h-2 rounded-full bg-red-500 shadow-[0_0_8px_#EF4444] animate-pulse" /> BUFFER LOGGED
                </span>
              ) : (
                <span className="text-[11px] font-mono text-slate-600 flex items-center gap-1.5">
                  <span className="w-2 h-2 rounded-full bg-slate-800" /> IDLE SYSTEM
                </span>
              )}
            </div>
          </div>
        </div>
      </header>

      {/* Main stage */}
      <main className="flex-grow max-w-7xl w-full mx-auto p-4 sm:p-6 lg:p-8 flex flex-col justify-center">
        
        <AnimatePresence mode="wait">

          {/* VIEW 1: UPLOAD SCREEN */}
          {view === 'upload' && (
            <motion.div
              key="upload-view"
              initial={{ opacity: 0, y: 15 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -15 }}
              transition={{ duration: 0.25, ease: 'easeOut' }}
              className="max-w-2xl w-full mx-auto"
            >
              {/* YouTube Callout Banner */}
              <div className="bg-[#10070b] border border-red-500/25 rounded-3xl p-5 mb-6 flex flex-col sm:flex-row items-center justify-between gap-5 shadow-[0_0_25px_rgba(239,68,68,0.08)] relative overflow-hidden group">
                <div className="absolute top-0 right-0 w-32 h-32 bg-red-600/5 blur-3xl pointer-events-none rounded-full" />
                <div className="flex items-center gap-4 text-left">
                  <div className="w-12 h-12 bg-red-500/10 border border-red-500/25 rounded-2xl flex items-center justify-center shrink-0 shadow-[0_0_15px_rgba(239,68,68,0.15)] group-hover:scale-105 transition-transform duration-300">
                    <Youtube className="w-6 h-6 text-red-500" />
                  </div>
                  <div>
                    <h3 className="text-sm font-bold text-white uppercase tracking-wider font-display">
                      SUPPORT INTERNAL X CHEATS
                    </h3>
                    <p className="text-xs text-slate-400 mt-1 max-w-sm leading-relaxed">
                      Please support us by subscribing to our YouTube channel before exploring our offsets & tools!
                    </p>
                  </div>
                </div>
                <a 
                  href="https://www.youtube.com/@internalxcheat" 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="w-full sm:w-auto text-xs font-bold uppercase tracking-wider font-display bg-red-600 hover:bg-red-500 text-white px-5 py-3 rounded-xl transition-all shadow-[0_0_20px_rgba(220,38,38,0.35)] flex items-center justify-center gap-2 hover:scale-105 active:scale-95 cursor-pointer shrink-0"
                >
                  <Youtube className="w-4 h-4" />
                  <span>SUBSCRIBE CHANNEL</span>
                </a>
              </div>

              <div 
                onDragOver={handleDragOver}
                onDragLeave={handleDragLeave}
                onDrop={handleDrop}
                className={`bg-[#0d0d14]/90 backdrop-blur-xl border rounded-3xl p-8 text-center relative overflow-hidden transition-all duration-300 shadow-2xl ${
                  isDragging 
                    ? 'border-red-500 bg-red-500/5 shadow-[0_0_40px_rgba(239,68,68,0.15)]Scale scale-[1.01]' 
                    : 'border-red-950/30 hover:border-red-500/20'
                }`}
              >
                {/* Dragging state overlay */}
                <div className={`absolute inset-0 bg-[#08080c]/90 z-20 flex flex-col items-center justify-center transition-opacity duration-300 pointer-events-none ${isDragging ? 'opacity-100' : 'opacity-0'}`}>
                  <Upload className="w-14 h-14 text-red-500 mb-3 animate-bounce" />
                  <p className="text-base font-bold text-red-400 font-display">Drop your dump.cs file here</p>
                  <p className="text-xs text-slate-500 mt-1">Release to start instant automatic mapper scan</p>
                </div>

                <div className="w-16 h-16 bg-red-950/20 border border-red-500/20 rounded-2xl flex items-center justify-center mx-auto mb-6 shadow-[0_0_15px_rgba(239,68,68,0.1)]">
                  <Upload className="w-7 h-7 text-red-500" />
                </div>

                <h2 className="text-2xl font-bold tracking-tight text-white mb-2 font-display">
                  Analyze Unity <span className="text-red-500">dump.cs</span> Offsets
                </h2>
                
                <p className="text-sm text-slate-400 max-w-md mx-auto leading-relaxed mb-8">
                  Upload your C# class dump file to automatically extract RVA values for predefined features. Everything is processed 100% locally inside your web browser.
                </p>

                {errorMessage && (
                  <div className="mb-6 p-3 bg-red-500/10 border border-red-500/20 rounded-xl text-red-400 text-xs font-semibold flex items-center justify-center gap-2">
                    <X className="w-4 h-4 shrink-0 cursor-pointer" onClick={() => setErrorMessage('')} />
                    <span>{errorMessage}</span>
                  </div>
                )}

                <div className="flex justify-center">
                  <button
                    onClick={triggerFileBrowser}
                    className="w-full sm:w-auto px-8 py-4 bg-gradient-to-r from-red-600 to-red-500 hover:from-red-500 hover:to-red-400 text-white font-bold font-display text-xs rounded-xl shadow-[0_0_20px_rgba(239,68,68,0.3)] hover:shadow-[0_0_25px_rgba(239,68,68,0.45)] hover:scale-[1.02] transition-all cursor-pointer uppercase tracking-wider"
                  >
                    SELECT DUMP.CS FILE
                  </button>
                </div>

                <input 
                  type="file" 
                  ref={fileInputRef} 
                  onChange={handleFileChange} 
                  accept=".cs,.txt" 
                  className="hidden" 
                />

                <div className="mt-8 pt-6 border-t border-red-950/20 flex items-center justify-center gap-8 text-[11px] text-slate-500 font-mono uppercase">
                  <span className="flex items-center gap-1.5">
                    <CheckCircle2 className="w-3.5 h-3.5 text-red-500/60" /> BROWSER PERSISTENT
                  </span>
                  <span className="flex items-center gap-1.5">
                    <CheckCircle2 className="w-3.5 h-3.5 text-red-500/60" /> 100% OFFLINE SECURE
                  </span>
                </div>
              </div>
            </motion.div>
          )}

          {/* VIEW 2: PREMIUM LOADING / SCANNING SCREEN */}
          {view === 'scanning' && (
            <motion.div
              key="scanning-view"
              initial={{ opacity: 0, scale: 0.98 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 0.2 }}
              className="max-w-md w-full mx-auto text-center"
            >
              <div className="bg-[#0d0d14]/90 backdrop-blur-xl border border-red-500/10 rounded-3xl p-10 shadow-2xl relative">
                
                {/* Glowing Spinner */}
                <div className="relative w-20 h-20 mx-auto mb-8">
                  <div className="absolute inset-0 rounded-full border-4 border-red-950/30"></div>
                  <div className="absolute inset-0 rounded-full border-4 border-t-red-500 border-r-red-500/40 animate-spin"></div>
                  <div className="absolute inset-2 bg-[#08080c] rounded-full flex items-center justify-center">
                    <Flame className="w-7 h-7 text-red-500 animate-pulse" />
                  </div>
                </div>

                {/* Loading Messages */}
                <h3 className="text-xl font-bold text-white mb-2 font-display">
                  Scanning dump.cs...
                </h3>
                <p className="text-sm text-slate-400 font-medium mb-6 animate-pulse">
                  Please wait...
                </p>

                {/* Smooth Progress Bar */}
                <div className="space-y-2 max-w-xs mx-auto">
                  <div className="w-full bg-red-950/20 h-2 rounded-full overflow-hidden border border-red-500/10 p-[1px]">
                    <div 
                      className="bg-gradient-to-r from-red-600 to-red-500 h-full rounded-full transition-all duration-150 shadow-[0_0_10px_#EF4444]"
                      style={{ width: `${bulkScanProgress}%` }}
                    ></div>
                  </div>
                  <div className="flex justify-between items-center text-[10px] font-mono text-slate-500 uppercase tracking-widest font-bold">
                    <span>STATUS: PARSING</span>
                    <span className="text-red-400 font-bold">{bulkScanProgress}%</span>
                  </div>
                </div>

                <div className="absolute bottom-4 left-0 right-0 text-[9px] text-slate-600 font-mono uppercase tracking-widest text-center pointer-events-none">
                  Do not reload page during operation
                </div>
              </div>
            </motion.div>
          )}

          {/* VIEW 3: MAIN RESULTS DASHBOARD */}
          {view === 'results' && (
            <motion.div
              key="results-view"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 0.25 }}
              className="space-y-6"
            >
              
              {/* Dashboard Action Toolbar */}
              <div className="bg-[#0d0d14]/80 backdrop-blur-md border border-red-950/30 rounded-2xl p-4 flex flex-col md:flex-row items-center justify-between gap-4 shadow-xl">
                <div className="flex items-center gap-3 w-full md:w-auto">
                  <div className="p-2 bg-red-950/20 border border-red-500/20 rounded-xl">
                    <FileCode className="w-5 h-5 text-red-500" />
                  </div>
                  <div className="truncate">
                    <div className="flex items-center gap-2">
                      <span className="text-sm font-bold text-white font-mono truncate max-w-[200px] sm:max-w-xs">{fileName}</span>
                      {isDemo && (
                        <span className="text-[9px] bg-red-500/10 text-red-400 border border-red-500/25 px-2 py-0.5 rounded font-mono uppercase font-bold tracking-widest">SANDBOX</span>
                      )}
                    </div>
                    <p className="text-[10px] text-slate-500 font-mono mt-0.5">SIZE: {formattedFileSize} • LINES: {lineCount.toLocaleString()}</p>
                  </div>
                </div>

                <div className="flex flex-wrap items-center gap-2.5 w-full md:w-auto justify-end">
                  <button
                    onClick={triggerFileBrowser}
                    className="flex-1 sm:flex-none px-4 py-2 bg-slate-900 border border-red-500/20 hover:border-red-500/40 hover:bg-red-950/10 text-red-400 hover:text-red-300 text-xs font-bold font-display rounded-xl tracking-wider uppercase transition-all cursor-pointer flex items-center justify-center gap-1.5"
                  >
                    <Upload className="w-3.5 h-3.5" /> UPLOAD NEW
                  </button>
                  <button
                    onClick={() => copyToClipboard(getFormattedResultsText(), 'all-features')}
                    className="flex-1 sm:flex-none px-4 py-2 bg-gradient-to-r from-red-600 to-red-500 hover:from-red-500 hover:to-red-400 text-white text-xs font-bold font-display rounded-xl tracking-wider uppercase transition-all shadow-[0_0_15px_rgba(239,68,68,0.25)] cursor-pointer flex items-center justify-center gap-1.5"
                  >
                    {copiedId === 'all-features' ? (
                      <>
                        <Check className="w-3.5 h-3.5 text-white" />
                        <span>COPIED ALL RESULTS!</span>
                      </>
                    ) : (
                      <>
                        <Copy className="w-3.5 h-3.5 text-white" />
                        <span>COPY ALL RESULTS</span>
                      </>
                    )}
                  </button>
                  <button
                    onClick={handleClear}
                    className="px-3 py-2 bg-zinc-950 border border-slate-800 text-slate-400 hover:text-red-400 hover:border-red-500/30 rounded-xl text-xs font-bold tracking-wider transition-all cursor-pointer"
                    title="Clear system state"
                  >
                    <Trash2 className="w-3.5 h-3.5" />
                  </button>
                </div>
              </div>

              {/* Main Content Sections split: Search & results listing */}
              <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
                
                {/* LEFT LIST PANEL: grid of mapped RVA values (Col 9) */}
                <div className="lg:col-span-9 space-y-6">
                  
                  {/* Search bar & view toggle row */}
                  <div className="bg-[#0d0d14]/80 backdrop-blur-md border border-red-950/30 rounded-2xl p-4.5 shadow-xl flex flex-col md:flex-row items-center justify-between gap-4">
                    <div className="relative w-full md:max-w-md">
                      <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-4.5 h-4.5 text-slate-500" />
                      <input 
                        type="text"
                        value={searchQuery}
                        onChange={(e) => setSearchQuery(e.target.value)}
                        placeholder="Search predefined features (e.g. FPS, Gun, Ammo)..."
                        className="w-full bg-[#050508] border border-red-950/40 focus:border-red-500 rounded-xl pl-11 pr-14 py-2.5 text-xs text-white placeholder-slate-600 outline-none transition-all font-mono select-text"
                        autoComplete="off"
                        autoCorrect="off"
                        autoCapitalize="none"
                        spellCheck="false"
                      />
                      {searchQuery && (
                        <button 
                          onClick={() => setSearchQuery('')}
                          className="absolute right-4 top-1/2 -translate-y-1/2 text-[10px] uppercase font-bold text-slate-500 hover:text-red-400 font-mono cursor-pointer"
                        >
                          Clear
                        </button>
                      )}
                    </div>

                    <div className="flex items-center gap-3 w-full md:w-auto justify-end">
                      <div className="flex items-center gap-1.5 bg-[#050508] border border-red-950/40 p-1 rounded-xl">
                        <button
                          onClick={() => setResultsLayout('cards')}
                          className={`px-3 py-1.5 rounded-lg text-[10px] font-bold font-display tracking-widest transition-all cursor-pointer flex items-center gap-1 ${
                            resultsLayout === 'cards'
                              ? 'bg-red-500/10 border border-red-500/20 text-red-400'
                              : 'text-slate-500 hover:text-slate-300'
                          }`}
                        >
                          <Grid className="w-3 h-3" /> CARDS
                        </button>
                        <button
                          onClick={() => setResultsLayout('plain')}
                          className={`px-3 py-1.5 rounded-lg text-[10px] font-bold font-display tracking-widest transition-all cursor-pointer flex items-center gap-1 ${
                            resultsLayout === 'plain'
                              ? 'bg-red-500/10 border border-red-500/20 text-red-400'
                              : 'text-slate-500 hover:text-slate-300'
                          }`}
                        >
                          <Terminal className="w-3 h-3" /> PLAIN TEXT
                        </button>
                      </div>
                    </div>
                  </div>

                  {/* RESULTS CONTAINER */}
                  {resultsLayout === 'cards' ? (
                    <div>
                      {/* Section Header */}
                      <div className="flex items-center justify-between border-b border-red-950/20 pb-3 mb-4">
                        <h3 className="text-xs font-bold tracking-widest uppercase font-display text-red-400">FUNCTION</h3>
                        <span className="text-[10px] bg-red-950/20 border border-red-500/25 px-2 py-0.5 rounded-md font-mono text-red-400 font-bold">
                          {filteredFeatures.length} FEATURES SHOWING
                        </span>
                      </div>

                      {filteredFeatures.length === 0 ? (
                        <div className="bg-[#0d0d14]/50 border border-red-950/20 rounded-2xl py-16 text-center text-slate-500">
                          <Search className="w-10 h-10 mx-auto mb-3 text-slate-600 animate-pulse" />
                          <p className="text-xs uppercase font-bold tracking-widest text-slate-400">No Match Found</p>
                          <p className="text-[11px] text-slate-500 mt-1">Try adjusting your search filters</p>
                        </div>
                      ) : (
                        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
                          {filteredFeatures.map((feature, index) => {
                            const rva = bulkScanResults[feature] || 'Not Found';
                            const isFound = rva !== 'Not Found';
                            const mapping = SMART_MAPPINGS.find(m => m.feature === feature);
                            const isClickableType = isFound && mapping && ['bool', 'int', 'float'].includes(mapping.type);

                            return (
                              <motion.div
                                key={`card-${feature}-${index}`}
                                initial={{ opacity: 0, scale: 0.98 }}
                                animate={{ opacity: 1, scale: 1 }}
                                transition={{ duration: 0.2 }}
                                onClick={() => {
                                  if (isClickableType) {
                                    const { body, funcName } = getFunctionBodyForFeature(feature, rva, fileContent);
                                    setSelectedFeatureForModal(feature);
                                    setModalFunctionBody(body);
                                    setModalRva(rva);
                                    setModalType(mapping.type);
                                    setModalFuncName(funcName);
                                  } else {
                                    copyToClipboard(rva, `card-rva-${index}`);
                                  }
                                }}
                                className={`bg-[#0d0d14]/80 border rounded-2xl p-5 flex flex-col justify-between gap-4 cursor-pointer relative group transition-all duration-350 overflow-hidden ${
                                  isFound 
                                    ? isClickableType 
                                      ? 'border-red-950/40 hover:border-red-500/60 hover:bg-red-500/10 hover:shadow-[0_0_25px_rgba(239,68,68,0.12)]' 
                                      : 'border-red-950/40 hover:border-red-500/40 hover:bg-red-500/5 hover:shadow-[0_0_20px_rgba(239,68,68,0.06)]' 
                                    : 'border-slate-900 opacity-60 hover:opacity-100 hover:border-red-500/10'
                                }`}
                              >
                                <div className="flex items-start justify-between gap-3">
                                  <div>
                                    <h4 className="text-xs font-bold text-white tracking-wide group-hover:text-red-400 transition-colors font-display">
                                      {feature}
                                    </h4>
                                    <span className="text-[9px] uppercase font-mono tracking-widest text-slate-600 mt-1 block">IDENTIFIED ATTRIBUTE</span>
                                  </div>
                                  <div className="flex flex-col items-end gap-1 shrink-0">
                                    <span className={`text-[9px] font-mono px-2 py-0.5 border rounded-md font-bold uppercase transition-all ${
                                      isFound && mapping ? (
                                        mapping.type === 'bool' ? 'bg-rose-500/10 border-rose-500/25 text-rose-400' :
                                        mapping.type === 'int' ? 'bg-blue-500/10 border-blue-500/25 text-blue-400' :
                                        mapping.type === 'float' ? 'bg-amber-500/10 border-amber-500/25 text-amber-400' :
                                        'bg-red-500/10 border-red-500/20 text-red-400'
                                      ) : 'bg-slate-900 border-slate-800 text-slate-500'
                                    }`}>
                                      {isFound && mapping ? mapping.type : 'FUNC'}
                                    </span>
                                  </div>
                                </div>

                                <div className="border-t border-red-950/15 pt-3 flex items-center justify-between">
                                  <span className={`text-[10px] font-mono transition-colors ${
                                    isClickableType ? 'text-red-400 font-bold group-hover:text-red-300' : 'text-slate-500'
                                  }`}>
                                    {isClickableType ? 'VIEW CODE ➔' : 'RVA:'}
                                  </span>
                                  <span className={`text-xs font-bold font-mono tracking-wide ${
                                    isFound 
                                      ? 'text-red-400 group-hover:text-red-300 drop-shadow-[0_0_6px_rgba(239,68,68,0.2)]' 
                                      : 'text-slate-600'
                                  }`}>
                                    {rva}
                                  </span>
                                </div>

                                {/* Copied message notification badge */}
                                <AnimatePresence>
                                  {copiedId === `card-rva-${index}` && (
                                    <motion.div 
                                      initial={{ opacity: 0, y: 10 }}
                                      animate={{ opacity: 1, y: 0 }}
                                      exit={{ opacity: 0, y: -10 }}
                                      className="absolute inset-0 bg-[#0d0d14]/95 backdrop-blur-sm flex items-center justify-center gap-2 z-10"
                                    >
                                      <Check className="w-4 h-4 text-red-500" />
                                      <span className="text-xs font-bold text-red-400 font-display uppercase tracking-wider">COPIED RVA</span>
                                    </motion.div>
                                  )}
                                </AnimatePresence>
                              </motion.div>
                            );
                          })}
                        </div>
                      )}
                    </div>
                  ) : (
                    <div className="bg-[#050508] border border-red-950/30 rounded-2xl p-5 shadow-2xl relative">
                      <div className="flex justify-between items-center pb-3 mb-4 border-b border-red-950/20">
                        <span className="text-[10px] font-mono uppercase tracking-widest text-slate-500">RAW TERMINAL DISPLAY (FUNCTION ONLY)</span>
                        <button
                          onClick={() => copyToClipboard(getFormattedResultsText(searchQuery), 'plain-raw-box')}
                          className="text-[10px] font-mono font-bold bg-slate-900 border border-red-500/20 hover:border-red-500/40 text-red-400 hover:text-red-300 px-3 py-1.5 rounded-lg transition-all cursor-pointer flex items-center gap-1.5"
                        >
                          {copiedId === 'plain-raw-box' ? 'COPIED!' : 'COPY'}
                        </button>
                      </div>
                      <pre className="text-slate-300 font-mono text-[11px] sm:text-xs overflow-x-auto whitespace-pre leading-relaxed p-4 bg-[#08080c] rounded-xl border border-red-950/20 max-h-[500px] select-text">
                        {getFormattedResultsText(searchQuery)}
                      </pre>
                    </div>
                  )}

                </div>

                {/* RIGHT SYSTEM PANEL: details & diagnostics (Col 3) */}
                <div className="lg:col-span-3 space-y-6">
                  
                  {/* Scan Info Widget */}
                  <div className="bg-[#0d0d14]/80 backdrop-blur-md border border-red-950/30 rounded-2xl p-5 shadow-xl">
                    <h3 className="text-xs font-bold tracking-widest uppercase text-white font-display border-b border-red-950/20 pb-3 mb-4 flex items-center gap-1.5">
                      <Flame className="w-4 h-4 text-red-500" /> METRIC REPORT
                    </h3>

                    <div className="space-y-4 font-mono text-[11px]">
                      <div className="bg-[#050508] p-3 rounded-xl border border-red-950/20">
                        <span className="text-slate-500 text-[10px] uppercase block tracking-wider font-semibold">Active Offsets</span>
                        <span className="text-sm font-bold text-white">
                          {Object.values(bulkScanResults).filter(v => v !== 'Not Found').length} / {UNIQUE_FEATURES.length} FOUND
                        </span>
                      </div>
                      <div className="bg-[#050508] p-3 rounded-xl border border-red-950/20">
                        <span className="text-slate-500 text-[10px] uppercase block tracking-wider font-semibold">Scan Duration</span>
                        <span className="text-sm font-bold text-red-400">{bulkScanTime} ms</span>
                      </div>
                      <div className="bg-[#050508] p-3 rounded-xl border border-red-950/20">
                        <span className="text-slate-500 text-[10px] uppercase block tracking-wider font-semibold">Security Integrity</span>
                        <span className="text-[11px] text-green-500 font-bold flex items-center gap-1 mt-1">
                          ✓ SECURED CLIENT-SIDE
                        </span>
                      </div>
                    </div>
                  </div>

                  {/* System Explainer */}
                  <div className="bg-[#0d0d14]/80 backdrop-blur-md border border-red-950/30 rounded-2xl p-5 shadow-xl">
                    <h3 className="text-xs font-bold tracking-widest uppercase text-white font-display border-b border-red-950/20 pb-3 mb-3">
                      SYSTEM TIPS
                    </h3>
                    <p className="text-slate-400 text-xs leading-relaxed space-y-2">
                      Click any card to automatically copy its extracted RVA offset directly into your computer clipboard. Use plain text view for batch copying mappings.
                    </p>
                  </div>

                </div>

              </div>
            </motion.div>
          )}

        </AnimatePresence>

      </main>

      {/* Footer bar */}
      <footer className="mt-auto border-t border-red-950/20 bg-[#0d0d12]/50 py-5 px-6 flex flex-col sm:flex-row justify-between items-center gap-4 text-[10px] text-slate-600 font-mono uppercase tracking-widest">
        <div className="flex flex-wrap justify-center gap-6">
          <span>PIPELINE: SINGLE-SECTION FUNCTION</span>
          <span>SYSTEM ENGINE: STABILIZED</span>
          <span>BUFFER: CACHED-MEMORY</span>
        </div>
        <div className="text-center sm:text-right">
          CLIENT EXECUTED ONLY • LOCAL DUMP PARSER
        </div>
      </footer>

      {/* DETAILS PANEL / MODAL */}
      <AnimatePresence>
        {selectedFeatureForModal && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black/85 backdrop-blur-md z-50 flex items-center justify-center p-4 sm:p-6 md:p-10"
            onClick={() => setSelectedFeatureForModal(null)}
          >
            <motion.div
              initial={{ scale: 0.95, y: 20, opacity: 0 }}
              animate={{ scale: 1, y: 0, opacity: 1 }}
              exit={{ scale: 0.95, y: 20, opacity: 0 }}
              transition={{ type: 'spring', duration: 0.4 }}
              className="bg-[#09090d] border border-red-500/30 rounded-2xl w-full max-w-3xl max-h-[85vh] flex flex-col shadow-[0_0_50px_rgba(239,68,68,0.15)] overflow-hidden"
              onClick={(e) => e.stopPropagation()}
            >
              {/* Header */}
              <div className="border-b border-red-950/25 p-5 flex items-start justify-between bg-[#0e0e14]/90">
                <div className="space-y-1">
                  <div className="flex items-center gap-2">
                    <span className={`text-[9px] font-mono px-2 py-0.5 border rounded-md font-bold uppercase ${
                      modalType === 'bool' ? 'bg-[#ff0055]/10 border-[#ff0055]/25 text-[#ff4477]' :
                      modalType === 'int' ? 'bg-[#0077ff]/10 border-[#0077ff]/25 text-[#4499ff]' :
                      modalType === 'float' ? 'bg-[#ffaa00]/10 border-[#ffaa00]/25 text-[#ffcc44]' :
                      'bg-red-500/10 border-red-500/20 text-red-400'
                    }`}>
                      {modalType.toUpperCase()}
                    </span>
                    <h3 className="text-sm sm:text-base font-bold text-white font-display tracking-wide">
                      {selectedFeatureForModal}
                    </h3>
                  </div>
                  <p className="text-[10px] font-mono text-slate-500 uppercase tracking-widest">
                    FUNCTION DETECTED: <span className="text-red-400/80 font-bold">{modalFuncName}</span>
                  </p>
                </div>
                
                <button
                  onClick={() => setSelectedFeatureForModal(null)}
                  className="bg-slate-900 border border-slate-800 text-slate-400 hover:text-white hover:border-red-500/40 p-2 rounded-xl transition-all cursor-pointer"
                  id="close-modal-btn"
                >
                  <X className="w-4 h-4" />
                </button>
              </div>

              {/* Code Area */}
              <div className="flex-1 overflow-y-auto p-6 bg-[#040407] border-b border-red-950/20 custom-scrollbar select-text">
                {modalFunctionBody ? (
                  <div className="relative group/code">
                    <pre className="font-mono text-xs sm:text-[13px] leading-relaxed whitespace-pre-wrap select-text p-4 rounded-xl bg-[#07070b] border border-red-950/15 min-h-[120px] overflow-auto">
                      {highlightCSharp(modalFunctionBody)}
                    </pre>
                  </div>
                ) : (
                  <div className="flex flex-col items-center justify-center py-12 text-slate-500 font-mono text-xs">
                    <Terminal className="w-8 h-8 text-slate-600 mb-2 animate-pulse" />
                    <span>COULD NOT LOCATE FUNCTION BODY IN FILE</span>
                  </div>
                )}
              </div>

              {/* Action Buttons Footer */}
              <div className="p-5 bg-[#0e0e14]/90 flex flex-wrap items-center justify-between gap-3">
                {/* RVA Display */}
                <div className="bg-slate-950 border border-slate-900 rounded-xl px-4 py-2 flex items-center gap-3">
                  <span className="text-[10px] font-mono text-slate-500 uppercase tracking-wider font-semibold">RVA Offset:</span>
                  <span className="text-xs font-bold font-mono text-red-400 drop-shadow-[0_0_4px_rgba(239,68,68,0.3)]">{modalRva}</span>
                </div>

                <div className="flex items-center gap-2">
                  {/* Copy RVA */}
                  <button
                    onClick={() => {
                      navigator.clipboard.writeText(modalRva);
                      setModalCopiedType('rva');
                      setTimeout(() => setModalCopiedType(null), 1500);
                    }}
                    className="text-xs font-semibold uppercase tracking-wider font-display bg-slate-950 border border-slate-800 hover:border-red-500/30 text-slate-400 hover:text-red-300 px-4 py-2.5 rounded-xl transition-all cursor-pointer flex items-center gap-1.5"
                    id="copy-rva-btn"
                  >
                    {modalCopiedType === 'rva' ? (
                      <>
                        <Check className="w-3.5 h-3.5 text-red-500" />
                        <span>Copied RVA!</span>
                      </>
                    ) : (
                      <>
                        <Copy className="w-3.5 h-3.5" />
                        <span>Copy RVA</span>
                      </>
                    )}
                  </button>

                  {/* Copy Function */}
                  <button
                    onClick={() => {
                      navigator.clipboard.writeText(modalFunctionBody);
                      setModalCopiedType('code');
                      setTimeout(() => setModalCopiedType(null), 1500);
                    }}
                    className="text-xs font-bold uppercase tracking-wider font-display bg-red-600 hover:bg-red-500 text-white px-4 py-2.5 rounded-xl transition-all cursor-pointer flex items-center gap-1.5 shadow-[0_0_15px_rgba(220,38,38,0.3)]"
                    id="copy-func-btn"
                  >
                    {modalCopiedType === 'code' ? (
                      <>
                        <Check className="w-3.5 h-3.5" />
                        <span>Copied Code!</span>
                      </>
                    ) : (
                      <>
                        <FileCode className="w-3.5 h-3.5" />
                        <span>Copy Function</span>
                      </>
                    )}
                  </button>
                </div>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
      
    </div>
  );
}
